config/routes.rb
Rails.application.routes.draw do
  get 'tools/import_students'
  post 'tools/do_import_students'

  resources :articles

  devise_for :users
  ActiveAdmin.routes(self)

  namespace :api do
    namespace :v1 do
      get 'work_papers', to: 'work_papers#index'
      get 'work_papers/:work_paper_id/home_works', to: 'home_works#index'

      get 'media', to: 'media_resources#index'
      post 'media/search', to: 'media_resources#search'

      resources :work_papers do
        resources :media_resources
        resource :work_review
      end

      resources :home_works do
        resources :media_resources
        resource :work_review
        collection do
          get 'un_review'
        end
      end

      resources :users do
        resource :profile do
          post 'replace_avatar'
        end
      end

      resources :teachers do
        resources :work_reviews do
          collection do
            post 'batch_review'
          end
        end
        resource :profile
        resources :work_papers, shallow: true
        resources :school_classes
        resources :informs
        resources :votes do
          member do
            post 'choose'
            post 'close'
          end
        end
        member do
          post 'send_message_to_person'
          post 'send_message_to_class'
          get 'user_messages'
        end
      end

      resources :students do
        resource :profile
        resources :work_papers, shallow: true
        resources :home_works, shallow: true
        member do
          post 'send_message_to_person'
          post 'send_message_to_class'
          get 'user_messages'
        end
      end

      resources :user_tokens
      resources :school_classes do
        resources :work_papers, shallow: true
        resources :students
        resources :teachers
      end

      resources :user_messages, only: [:index, :show]

      resources :posts do
        resources :comments
      end
    end
  end

  root :to => 'home#index'

end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController

  def import_students
  end

  def do_import_students
  	if !params[:school_class].blank? and params[:students]
	  	@sc = params[:school_class]
	  	@is_old_class = SchoolClass.find_by_class_no @sc
	  	if !@is_old_class
		  	@students = params[:students].read.force_encoding("UTF-8")
		  	process_students
		  else
		  	flash.now[:error] = "#{@sc}班级已经存在！"
		  end
		else 
			flash.now[:error] = '输入不完整！'
		end
  end

  private

  def process_students
  end

end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/tools/do_import_students.html.erb
<h3>新建班级，导入学生</h3>
	<br/>
	<br/>

<% if flash[:error] %>
  <div class="warning"><%= flash[:error] %></div>
<% else %>

	<h4><%= @sc %><br/></h4>
	<% if !@is_old_class %>
		导入完成！
		<br/>
		<br/>
		<% @students.each_line do |l| %>
			<%= l %> <br/>
		<% end %>
	<% end %>

<% end %>
<br/>
<br/>
<%= link_to '回退', tools_import_students_path %>

app/views/tools/import_students.html.erb
<h3>新建班级，导入学生</h3>
	<br/>
	<br/>

<%= form_tag('/tools/do_import_students', multipart: true) do %>
	<b>班级名称：</b>
	<br/>
	<br/>
	<%= text_field_tag 'school_class' %>
	<br/>
	<br/>
	<b>学生名单文件：</b>
	<br/>
	<br/>
	<%= file_field_tag 'students' %>
	<br/>
	<br/>
	<%= submit_tag '提交' %>
<% end %>